spring:
  application:
    name: WebApp
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;databaseName=test_gardening_spring;encrypt=true;trustServerCertificate=true
    username: sa
    password: 753159852
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    hibernate:
      ddl-auto: update